### ISSUE TITLE
Introduction section has reponsivity issues

### ISSUE THREAD

**Issue by Wyctus** [myscoutee/myscoutee#1]
![kép](https://user-images.githubusercontent.com/28842070/128626678-8547c879-6f00-4077-ae21-0787ec499dad.png)

**Comment by fssrepository** [comment]
I take this note, however it has been planned as a hybrid mobil app, to use localization or notification does not work on desktop well. Planning to deploy to appstore.

**Comment by fssrepository** [comment]
Although my components are responsive, but the 3rd party ones are not (even the angular one).
Although added that fix for the entry page, but requires complete style rework (even font and navigation bar) on the angular ones.
Other pages are not that bad, than this entry page.

**Comment by Wyctus** [comment]
Great to see the progress!

**Comment by fssrepository** [comment]
![image](https://user-images.githubusercontent.com/45578746/129040475-eecd5556-f57c-4b56-b516-c8903b19930c.png)

For temporary fix.

**Comment by fssrepository** [comment]
The app has been upgraded, to move faster, i'm wiping out registrations for a while. Almost fully featured app and more dense explanation video will be available in the coming week. There is 3 flow, one is working with notifications, other two needs to be finished.
